spring:
  config:
    activate:
      on-profile: local
  security:
    user:
      name: user
      password: localpass

server:
  port: 8081

external-api:
  character-service:
    url: localhost
    port: 8000
  game-session-service:
    url: localhost
    port: 8001

logging:
  level:
    org.springframework: DEBUG
    com.kanionland: DEBUG
